# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 217117324c9bb68e95c48e2ced929501f2c645a1c3b590cad54cad9244070c216c11bb2e2ad031252b30701574debff437e3daf5795485c9ba098416d2da54d2

test:
  secret_key_base: 20c037712ad1ff007712e009b13b497bfae80c3b84bc3bd18a415f1c412de780a1a0e9a4e38b74524e88e5481f5863017088306829a56b93419784173ba530eb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
